project:
  type: book

book:
  title: "PHCM9795: Foundations of Biostatistics"
  author: "Timothy Dobbins"
  date: "Term 2, 2023"
  chapters:
    - index.qmd
    - intro.qmd
    - 03-precision.qmd
    - 03.1-precision-stata.qmd
    - 03.2-precision-R.qmd
    - 03.3-precision-activities.qmd
    - 04-hypothesis-testing.qmd
    - 04.1-hypothesis-testing-stata.qmd
    - 04.2-hypothesis-testing-R.qmd
    - 04.3-hypothesis-testing-activities.qmd
    - 05-comparing-two-means.qmd
    - 05.1-comparing-two-means-stata.qmd
    - 05.2-comparing-two-means-R.qmd
    - 05.3-comparing-two-means-activities.qmd
    - 08-correlation-and-regression.qmd
    - 08.1-correlation-and-regression-stata.qmd
    - 08.2-correlation-and-regression-R.qmd
    - 08.3-correlation-and-regression-activities.qmd
    - references.qmd

bibliography: PHCM9795.bib

pdf-engine: xelatex

format:
  html:
    theme: cosmo
  pdf:
    papersize: A4
    documentclass: memoir
    mainfont: Roboto
    sansfont: Clancy
    include-in-header: preamble.tex
